# Generated by Django 5.1.2 on 2025-05-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_remove_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons/"),
        ),
    ]
