# Generated by Django 5.1.2 on 2025-05-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_remove_order_status_updateorderstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
