# Generated by Django 5.1.2 on 2025-05-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_product_expired_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="posted_by",
        ),
    ]
