# Generated by Django 5.1.2 on 2025-05-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_order_delivery_status_order_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UpdateOrderStatus",
        ),
    ]
