# Generated by Django 5.1.2 on 2025-05-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_delete_updateorderstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscribe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
